--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ReinfyTeam/Zuri-Rewrite
build-by-default: true
branches:
- main
projects:
  ZuriLite:
    path: ""
    lint: false
    icon: "icon.png"
...
