---
name: ZuriLite 
description: A lightweight anticheat optimized for combat-relative servers!
authors: [ReinfyTeam, xqwtxon, xwertxy]
version: 1.0.0
website: "https://github.com/ReinfyTeam/ZuriLite/"
src-namespace-prefix: ReinfyTeam\ZuriLite
main: ReinfyTeam\ZuriLite\ZuriLiteAC
api: 5.0.0
permissions:
     zuri.command:
          default: op
          description: ZuriLite command.
...
